# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /mnt/Extend/Programs/unreal-engine
GAMEPROJECTFILE =/home/main/Project/CoreMechanic/CoreMechanic.uproject

TARGETS = \
	CoreMechanic-Linux-Debug  \
	CoreMechanic-Linux-DebugGame  \
	CoreMechanic-Linux-Test  \
	CoreMechanic-Linux-Shipping  \
	CoreMechanic \
	CoreMechanicEditor-Linux-Debug  \
	CoreMechanicEditor-Linux-DebugGame  \
	CoreMechanicEditor-Linux-Test  \
	CoreMechanicEditor-Linux-Shipping  \
	CoreMechanicEditor \
	UnrealClient-Linux-Debug  \
	UnrealClient-Linux-DebugGame  \
	UnrealClient-Linux-Test  \
	UnrealClient-Linux-Shipping  \
	UnrealClient \
	UnrealEditor-Linux-Debug  \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Test  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-Debug  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Test  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	UnrealServer-Linux-Debug  \
	UnrealServer-Linux-DebugGame  \
	UnrealServer-Linux-Test  \
	UnrealServer-Linux-Shipping  \
	UnrealServer\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend CoreMechanicEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug CoreMechanicEditor-Linux-Debug


CoreMechanic-Linux-Debug:
	 $(PROJECTBUILD) CoreMechanic Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

CoreMechanic-Linux-DebugGame:
	 $(PROJECTBUILD) CoreMechanic Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

CoreMechanic-Linux-Test:
	 $(PROJECTBUILD) CoreMechanic Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

CoreMechanic-Linux-Shipping:
	 $(PROJECTBUILD) CoreMechanic Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

CoreMechanic:
	 $(PROJECTBUILD) CoreMechanic Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

CoreMechanicEditor-Linux-Debug:
	 $(PROJECTBUILD) CoreMechanicEditor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

CoreMechanicEditor-Linux-DebugGame:
	 $(PROJECTBUILD) CoreMechanicEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

CoreMechanicEditor-Linux-Test:
	 $(PROJECTBUILD) CoreMechanicEditor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

CoreMechanicEditor-Linux-Shipping:
	 $(PROJECTBUILD) CoreMechanicEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

CoreMechanicEditor:
	 $(PROJECTBUILD) CoreMechanicEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient-Linux-Debug:
	 $(BUILD) UnrealClient Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient-Linux-DebugGame:
	 $(BUILD) UnrealClient Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient-Linux-Test:
	 $(BUILD) UnrealClient Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient-Linux-Shipping:
	 $(BUILD) UnrealClient Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient:
	 $(BUILD) UnrealClient Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Debug:
	 $(BUILD) UnrealEditor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Test:
	 $(BUILD) UnrealEditor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Debug:
	 $(BUILD) UnrealGame Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Test:
	 $(BUILD) UnrealGame Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer-Linux-Debug:
	 $(BUILD) UnrealServer Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer-Linux-DebugGame:
	 $(BUILD) UnrealServer Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer-Linux-Test:
	 $(BUILD) UnrealServer Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer-Linux-Shipping:
	 $(BUILD) UnrealServer Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer:
	 $(BUILD) UnrealServer Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
